In [1]:
import sqlite3
import pandas as pd
from pathlib import Path

In [2]:
DB_PATH = Path("/home/jovyan/work-easi-eds/data copy/eds_database.db")

print(DB_PATH)
print(DB_PATH.exists())

/home/jovyan/work-easi-eds/data copy/eds_database.db
True

In [3]:
conn = sqlite3.connect(DB_PATH)

print("Connected successfully")

Connected successfully

In [4]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table'
ORDER BY name;
"""

tables_df = pd.read_sql_query(query, conn)

tables_df

                          name
0                   auth_group
1       auth_group_permissions
2              auth_permission
3                    auth_user
4             auth_user_groups
5   auth_user_user_permissions
6             django_admin_log
7          django_content_type
8            django_migrations
9               django_session
10            eds_easi_tilerun
11               landsat_tiles
12             sqlite_sequence

In [5]:
for table in tables_df['name']:
    print(table)

auth_group
auth_group_permissions
auth_permission
auth_user
auth_user_groups
auth_user_user_permissions
django_admin_log
django_content_type
django_migrations
django_session
eds_easi_tilerun
landsat_tiles
sqlite_sequence

In [6]:
row_counts = []

for table in tables_df['name']:
    try:
        count_query = f"SELECT COUNT(*) AS count FROM {table}"
        count = pd.read_sql_query(count_query, conn).iloc[0]['count']

        row_counts.append({
            'table': table,
            'rows': count
        })

    except Exception as e:
        row_counts.append({
            'table': table,
            'rows': f'ERROR: {e}'
        })

row_counts_df = pd.DataFrame(row_counts)
row_counts_df.sort_values('rows', ascending=False)

                         table  rows
11               landsat_tiles   466
2              auth_permission    56
8            django_migrations    23
7          django_content_type    14
12             sqlite_sequence     7
4             auth_user_groups     0
3                    auth_user     0
1       auth_group_permissions     0
0                   auth_group     0
5   auth_user_user_permissions     0
6             django_admin_log     0
10            eds_easi_tilerun     0
9               django_session     0