In [1]:
import boto3
import pandas as pd
from pathlib import PurePosixPath
import re

client = boto3.client("s3")
bucket = "dcceew-eds-data"

# Optional: set a prefix if you know it, otherwise use ""
prefix = ""

paginator = client.get_paginator("list_objects_v2")

rows = []
for page in paginator.paginate(Bucket=bucket, Prefix=prefix):
    for obj in page.get("Contents", []):
        key = obj["Key"]
        name = PurePosixPath(key).name
        suffix = PurePosixPath(key).suffix.lower()
        rows.append({
            "key": key,
            "file": name,
            "suffix": suffix,
            "size_MB": round(obj["Size"] / 1e6, 3),
            "last_modified": obj["LastModified"],
        })

df = pd.DataFrame(rows)

if df.empty:
    print("No objects found.")
else:
    display(df.head(50))
    print(f"Total objects: {len(df)}")

,key,file,suffix,size_MB,last_modified
0,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/manife...,p089r078_manifest.parquet,.parquet,0.006,2026-03-24 22:30:24+00:00
1,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/manife...,p089r079_manifest.parquet,.parquet,0.006,2026-03-04 23:21:05+00:00
2,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/manife...,p089r080_manifest.parquet,.parquet,0.006,2026-03-24 23:21:57+00:00
3,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150212_ga1-clr_e32756.tif,.tif,25.338,2026-03-24 22:36:14+00:00
4,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150212_ga2_e32756.tif,.tif,1.058,2026-03-24 22:36:15+00:00
5,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150228_ga1-clr_e32756.tif,.tif,28.767,2026-03-24 22:36:33+00:00
6,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150228_ga2_e32756.tif,.tif,1.025,2026-03-24 22:36:34+00:00
7,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150316_ga1-clr_e32756.tif,.tif,17.184,2026-03-24 22:36:52+00:00
8,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150316_ga2_e32756.tif,.tif,0.677,2026-03-24 22:36:53+00:00
9,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150503_ga1-clr_e32756.tif,.tif,40.711,2026-03-15 22:28:00+00:00
10,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150503_ga2_e32756.tif,.tif,0.672,2026-03-15 22:28:01+00:00
11,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150519_ga1-clr_e32756.tif,.tif,36.011,2026-03-15 22:28:17+00:00
12,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150519_ga2_e32756.tif,.tif,0.697,2026-03-15 22:28:17+00:00
13,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150604_ga1-clr_e32756.tif,.tif,38.015,2026-03-15 22:28:32+00:00
14,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150604_ga2_e32756.tif,.tif,0.369,2026-03-15 22:28:33+00:00
15,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150620_ga1-clr_e32756.tif,.tif,37.821,2026-03-15 22:28:48+00:00
16,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150620_ga2_e32756.tif,.tif,0.681,2026-03-15 22:28:48+00:00
17,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150706_ga1-clr_e32756.tif,.tif,37.235,2026-03-15 22:29:04+00:00
18,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150706_ga2_e32756.tif,.tif,0.247,2026-03-15 22:29:05+00:00
19,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150807_ga1-clr_e32756.tif,.tif,38.764,2026-03-15 22:29:20+00:00
20,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150807_ga2_e32756.tif,.tif,0.515,2026-03-15 22:29:21+00:00
21,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150823_ga1-clr_e32756.tif,.tif,19.123,2026-03-15 22:29:35+00:00
22,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150823_ga2_e32756.tif,.tif,0.817,2026-03-15 22:29:36+00:00
23,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150908_ga1-clr_e32756.tif,.tif,37.759,2026-03-15 22:29:50+00:00
24,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150908_ga2_e32756.tif,.tif,0.406,2026-03-15 22:29:51+00:00
25,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150924_ga1-clr_e32756.tif,.tif,37.453,2026-03-15 22:30:05+00:00
26,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20150924_ga2_e32756.tif,.tif,0.380,2026-03-15 22:30:06+00:00
27,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20151213_ga1-clr_e32756.tif,.tif,36.409,2026-03-15 22:30:21+00:00
28,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20151213_ga2_e32756.tif,.tif,0.682,2026-03-15 22:30:21+00:00
29,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160114_ga1-clr_e32756.tif,.tif,23.450,2026-03-15 22:30:36+00:00
30,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160114_ga2_e32756.tif,.tif,0.727,2026-03-15 22:30:36+00:00
31,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160302_ga1-clr_e32756.tif,.tif,27.941,2026-03-24 22:37:14+00:00
32,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160302_ga2_e32756.tif,.tif,1.344,2026-03-24 22:37:14+00:00
33,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160505_ga1-clr_e32756.tif,.tif,28.165,2026-03-15 22:30:50+00:00
34,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160505_ga2_e32756.tif,.tif,0.994,2026-03-15 22:30:50+00:00
35,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160606_ga1-clr_e32756.tif,.tif,35.546,2026-03-15 22:31:05+00:00
36,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160606_ga2_e32756.tif,.tif,0.257,2026-03-15 22:31:05+00:00
37,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160622_ga1-clr_e32756.tif,.tif,19.145,2026-03-15 22:31:20+00:00
38,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160622_ga2_e32756.tif,.tif,0.587,2026-03-15 22:31:21+00:00
39,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160708_ga1-clr_e32756.tif,.tif,42.954,2026-03-15 22:31:36+00:00
40,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160708_ga2_e32756.tif,.tif,0.885,2026-03-15 22:31:36+00:00
41,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160724_ga1-clr_e32756.tif,.tif,36.550,2026-03-15 22:31:51+00:00
42,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160724_ga2_e32756.tif,.tif,0.341,2026-03-15 22:31:52+00:00
43,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160809_ga1-clr_e32756.tif,.tif,34.385,2026-03-15 22:32:07+00:00
44,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160809_ga2_e32756.tif,.tif,0.372,2026-03-15 22:32:07+00:00
45,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160825_ga1-clr_e32756.tif,.tif,37.465,2026-03-15 22:32:22+00:00
46,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160825_ga2_e32756.tif,.tif,0.406,2026-03-15 22:32:22+00:00
47,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160926_ga1-clr_e32756.tif,.tif,11.517,2026-03-15 22:32:36+00:00
48,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20160926_ga2_e32756.tif,.tif,0.301,2026-03-15 22:32:37+00:00
49,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20161012_ga1-clr_e32756.tif,.tif,36.573,2026-03-15 22:32:52+00:00

Total objects: 12359

In [2]:
eds_regex = (
    r"(_dlj_e|dlj-dlj|ga0_)"
)

eds_df = df[df["file"].str.contains(eds_regex, case=False, regex=True)].copy()

display(eds_df.head(100))
print(f"EDS-like objects: {len(eds_df)}")

/tmp/ipykernel_67522/3291618547.py:5: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  eds_df = df[df["file"].str.contains(eds_regex, case=False, regex=True)].copy()

,key,file,suffix,size_MB,last_modified
342,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20250701_ga0_e32756.tif,.tif,366.299,2026-04-20 03:38:01+00:00
377,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20251208_ga0_e32756.tif,.tif,458.238,2026-03-15 23:17:15+00:00
382,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl9olre_p089r078_20260117_ga0_e32756.tif,.tif,459.914,2026-04-20 03:40:39+00:00
395,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_d2025070120251208_dlj-dlj-cle...,.tif,0.882,2026-03-15 23:19:12+00:00
396,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_d2025070120251208_dlj-dlj-str...,.tif,0.953,2026-03-15 23:19:12+00:00
...,...,...,...,...,...
1576,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r081_d2025082620260109_dlj-dlj-cle...,.shp,3.796,2026-03-16 01:29:09+00:00
1577,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r081_d2025082620260109_dlj-dlj-cle...,.shx,0.015,2026-03-16 01:29:09+00:00
1578,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r081_d2025082620260109_dlj-dlj-str...,.cpg,0.000,2026-03-16 01:29:07+00:00
1579,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r081_d2025082620260109_dlj-dlj-str...,.dbf,0.103,2026-03-16 01:29:08+00:00
1580,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r081_d2025082620260109_dlj-dlj-str...,.prj,0.000,2026-03-16 01:29:08+00:00

EDS-like objects: 777

In [3]:
import re

def extract_tile(fname):
    m = re.search(r"p\d{3}r\d{3}", fname.lower())
    return m.group(0) if m else None

eds_df["tile"] = eds_df["file"].apply(extract_tile)

eds_df.head()

,key,file,suffix,size_MB,last_modified,tile
342,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20250701_ga0_e32756.tif,.tif,366.299,2026-04-20 03:38:01+00:00,p089r078
377,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_20251208_ga0_e32756.tif,.tif,458.238,2026-03-15 23:17:15+00:00,p089r078
382,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl9olre_p089r078_20260117_ga0_e32756.tif,.tif,459.914,2026-04-20 03:40:39+00:00,p089r078
395,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_d2025070120251208_dlj-dlj-cle...,.tif,0.882,2026-03-15 23:19:12+00:00,p089r078
396,AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/...,sl8olre_p089r078_d2025070120251208_dlj-dlj-str...,.tif,0.953,2026-03-15 23:19:12+00:00,p089r078

In [4]:
tile_counts = (
    eds_df.groupby("tile")
    .size()
    .reset_index(name="file_count")
    .sort_values("tile")
)

display(tile_counts)

        tile  file_count
0   p089r078          29
1   p089r079          29
2   p089r080          29
3   p089r081          15
4   p089r082          15
5   p089r083          15
6   p089r084          15
7   p090r077          15
8   p090r078          15
9   p090r079          15
10  p090r080          15
11  p090r081          15
12  p090r082          15
13  p090r083          15
14  p090r084          15
15  p090r085          15
16  p090r086          15
17  p090r088          15
18  p090r089          15
19  p090r090          15
20  p091r076          15
21  p091r077          15
22  p091r078          15
23  p091r079          15
24  p091r080          15
25  p091r081          15
26  p091r082          15
27  p091r083          15
28  p091r084          29
29  p091r085          16
30  p091r086          16
31  p091r087          15
32  p091r089          15
33  p091r090          15
34  p092r075          29
35  p092r076          29
36  p092r077          15
37  p092r078          15
38  p092r079          15
39  p092r080          15
40  p092r081          15
41  p092r082          15
42  p092r083          15
43  p092r084          16
44  p115r078          15
45  p115r079          15

# Print out EDS results

In [5]:
for tile, group in eds_df.sort_values(["tile","file"]).groupby("tile"):
    
    print(f"\n--- {tile} ---")
    
    for f in group["file"]:
        print(f)

--- p089r078 ---
sl8olre_p089r078_20250701_ga0_e32756.tif
sl8olre_p089r078_20251208_ga0_e32756.tif
sl8olre_p089r078_d2025070120251208_dlj-dlj-clear-ge80_e32756.cpg
sl8olre_p089r078_d2025070120251208_dlj-dlj-clear-ge80_e32756.dbf
sl8olre_p089r078_d2025070120251208_dlj-dlj-clear-ge80_e32756.prj
sl8olre_p089r078_d2025070120251208_dlj-dlj-clear-ge80_e32756.shp
sl8olre_p089r078_d2025070120251208_dlj-dlj-clear-ge80_e32756.shx
sl8olre_p089r078_d2025070120251208_dlj-dlj-clear-ge80_e32756.tif
sl8olre_p089r078_d2025070120251208_dlj-dlj-strong-ge60_e32756.cpg
sl8olre_p089r078_d2025070120251208_dlj-dlj-strong-ge60_e32756.dbf
sl8olre_p089r078_d2025070120251208_dlj-dlj-strong-ge60_e32756.prj
sl8olre_p089r078_d2025070120251208_dlj-dlj-strong-ge60_e32756.shp
sl8olre_p089r078_d2025070120251208_dlj-dlj-strong-ge60_e32756.shx
sl8olre_p089r078_d2025070120251208_dlj-dlj-strong-ge60_e32756.tif
sl8olre_p089r078_d2025070120251208_dlj_e32756.tif
sl9olre_p089r078_20260117_ga0_e32756.tif
sl9olre_p089r078_d2025070120260117_dlj-dlj-clear-ge80_e32756.cpg
sl9olre_p089r078_d2025070120260117_dlj-dlj-clear-ge80_e32756.dbf
sl9olre_p089r078_d2025070120260117_dlj-dlj-clear-ge80_e32756.prj
sl9olre_p089r078_d2025070120260117_dlj-dlj-clear-ge80_e32756.shp
sl9olre_p089r078_d2025070120260117_dlj-dlj-clear-ge80_e32756.shx
sl9olre_p089r078_d2025070120260117_dlj-dlj-clear-ge80_e32756.tif
sl9olre_p089r078_d2025070120260117_dlj-dlj-strong-ge60_e32756.cpg
sl9olre_p089r078_d2025070120260117_dlj-dlj-strong-ge60_e32756.dbf
sl9olre_p089r078_d2025070120260117_dlj-dlj-strong-ge60_e32756.prj
sl9olre_p089r078_d2025070120260117_dlj-dlj-strong-ge60_e32756.shp
sl9olre_p089r078_d2025070120260117_dlj-dlj-strong-ge60_e32756.shx
sl9olre_p089r078_d2025070120260117_dlj-dlj-strong-ge60_e32756.tif
sl9olre_p089r078_d2025070120260117_dlj_e32756.tif

--- p089r079 ---
sl8olre_p089r079_20260109_ga0_e32756.tif
sl8olre_p089r079_20260125_ga0_e32756.tif
sl8olre_p089r079_d2025060720260109_dlj-dlj-clear-ge80_e32756.cpg
sl8olre_p089r079_d2025060720260109_dlj-dlj-clear-ge80_e32756.dbf
sl8olre_p089r079_d2025060720260109_dlj-dlj-clear-ge80_e32756.prj
sl8olre_p089r079_d2025060720260109_dlj-dlj-clear-ge80_e32756.shp
sl8olre_p089r079_d2025060720260109_dlj-dlj-clear-ge80_e32756.shx
sl8olre_p089r079_d2025060720260109_dlj-dlj-clear-ge80_e32756.tif
sl8olre_p089r079_d2025060720260109_dlj-dlj-strong-ge60_e32756.cpg
sl8olre_p089r079_d2025060720260109_dlj-dlj-strong-ge60_e32756.dbf
sl8olre_p089r079_d2025060720260109_dlj-dlj-strong-ge60_e32756.prj
sl8olre_p089r079_d2025060720260109_dlj-dlj-strong-ge60_e32756.shp
sl8olre_p089r079_d2025060720260109_dlj-dlj-strong-ge60_e32756.shx
sl8olre_p089r079_d2025060720260109_dlj-dlj-strong-ge60_e32756.tif
sl8olre_p089r079_d2025060720260109_dlj_e32756.tif
sl8olre_p089r079_d2025060720260125_dlj-dlj-clear-ge80_e32756.cpg
sl8olre_p089r079_d2025060720260125_dlj-dlj-clear-ge80_e32756.dbf
sl8olre_p089r079_d2025060720260125_dlj-dlj-clear-ge80_e32756.prj
sl8olre_p089r079_d2025060720260125_dlj-dlj-clear-ge80_e32756.shp
sl8olre_p089r079_d2025060720260125_dlj-dlj-clear-ge80_e32756.shx
sl8olre_p089r079_d2025060720260125_dlj-dlj-clear-ge80_e32756.tif
sl8olre_p089r079_d2025060720260125_dlj-dlj-strong-ge60_e32756.cpg
sl8olre_p089r079_d2025060720260125_dlj-dlj-strong-ge60_e32756.dbf
sl8olre_p089r079_d2025060720260125_dlj-dlj-strong-ge60_e32756.prj
sl8olre_p089r079_d2025060720260125_dlj-dlj-strong-ge60_e32756.shp
sl8olre_p089r079_d2025060720260125_dlj-dlj-strong-ge60_e32756.shx
sl8olre_p089r079_d2025060720260125_dlj-dlj-strong-ge60_e32756.tif
sl8olre_p089r079_d2025060720260125_dlj_e32756.tif
sl9olre_p089r079_20250607_ga0_e32756.tif

--- p089r080 ---
sl8olre_p089r080_20260109_ga0_e32756.tif
sl8olre_p089r080_20260125_ga0_e32756.tif
sl8olre_p089r080_d2025060720260109_dlj-dlj-clear-ge80_e32756.cpg
sl8olre_p089r080_d2025060720260109_dlj-dlj-clear-ge80_e32756.dbf
sl8olre_p089r080_d2025060720260109_dlj-dlj-clear-ge80_e32756.prj
sl8olre_p089r080_d2025060720260109_dlj-dlj-clear-ge80_e32756.shp
sl8olre_p089r080_d2025060720260109_dlj-dlj-clear-ge80_e32756.shx
sl8olre_p089r080_d2025060720260109_dlj-dlj-clear-ge80_e32756.tif
sl8olre_p089r080_d2025060720260109_dlj-dlj-strong-ge60_e32756.cpg
sl8olre_p089r080_d2025060720260109_dlj-dlj-strong-ge60_e32756.dbf
sl8olre_p089r080_d2025060720260109_dlj-dlj-strong-ge60_e32756.prj
sl8olre_p089r080_d2025060720260109_dlj-dlj-strong-ge60_e32756.shp
sl8olre_p089r080_d2025060720260109_dlj-dlj-strong-ge60_e32756.shx
sl8olre_p089r080_d2025060720260109_dlj-dlj-strong-ge60_e32756.tif
sl8olre_p089r080_d2025060720260109_dlj_e32756.tif
sl8olre_p089r080_d2025060720260125_dlj-dlj-clear-ge80_e32756.cpg
sl8olre_p089r080_d2025060720260125_dlj-dlj-clear-ge80_e32756.dbf
sl8olre_p089r080_d2025060720260125_dlj-dlj-clear-ge80_e32756.prj
sl8olre_p089r080_d2025060720260125_dlj-dlj-clear-ge80_e32756.shp
sl8olre_p089r080_d2025060720260125_dlj-dlj-clear-ge80_e32756.shx
sl8olre_p089r080_d2025060720260125_dlj-dlj-clear-ge80_e32756.tif
sl8olre_p089r080_d2025060720260125_dlj-dlj-strong-ge60_e32756.cpg
sl8olre_p089r080_d2025060720260125_dlj-dlj-strong-ge60_e32756.dbf
sl8olre_p089r080_d2025060720260125_dlj-dlj-strong-ge60_e32756.prj
sl8olre_p089r080_d2025060720260125_dlj-dlj-strong-ge60_e32756.shp
sl8olre_p089r080_d2025060720260125_dlj-dlj-strong-ge60_e32756.shx
sl8olre_p089r080_d2025060720260125_dlj-dlj-strong-ge60_e32756.tif
sl8olre_p089r080_d2025060720260125_dlj_e32756.tif
sl9olre_p089r080_20250607_ga0_e32756.tif

--- p089r081 ---
sl8olre_p089r081_20260109_ga0_e32756.tif
sl8olre_p089r081_d2025082620260109_dlj-dlj-clear-ge80_e32756.cpg
sl8olre_p089r081_d2025082620260109_dlj-dlj-clear-ge80_e32756.dbf
sl8olre_p089r081_d2025082620260109_dlj-dlj-clear-ge80_e32756.prj
sl8olre_p089r081_d2025082620260109_dlj-dlj-clear-ge80_e32756.shp
sl8olre_p089r081_d2025082620260109_dlj-dlj-clear-ge80_e32756.shx
sl8olre_p089r081_d2025082620260109_dlj-dlj-clear-ge80_e32756.tif
sl8olre_p089r081_d2025082620260109_dlj-dlj-strong-ge60_e32756.cpg
sl8olre_p089r081_d2025082620260109_dlj-dlj-strong-ge60_e32756.dbf
sl8olre_p089r081_d2025082620260109_dlj-dlj-strong-ge60_e32756.prj
sl8olre_p089r081_d2025082620260109_dlj-dlj-strong-ge60_e32756.shp
sl8olre_p089r081_d2025082620260109_dlj-dlj-strong-ge60_e32756.shx
sl8olre_p089r081_d2025082620260109_dlj-dlj-strong-ge60_e32756.tif
sl8olre_p089r081_d2025082620260109_dlj_e32756.tif
sl9olre_p089r081_20250826_ga0_e32756.tif

--- p089r082 ---
sl8olre_p089r082_20260109_ga0_e32756.tif
sl8olre_p089r082_d2025082620260109_dlj-dlj-clear-ge80_e32756.cpg
sl8olre_p089r082_d2025082620260109_dlj-dlj-clear-ge80_e32756.dbf
sl8olre_p089r082_d2025082620260109_dlj-dlj-clear-ge80_e32756.prj
sl8olre_p089r082_d2025082620260109_dlj-dlj-clear-ge80_e32756.shp
sl8olre_p089r082_d2025082620260109_dlj-dlj-clear-ge80_e32756.shx
sl8olre_p089r082_d2025082620260109_dlj-dlj-clear-ge80_e32756.tif
sl8olre_p089r082_d2025082620260109_dlj-dlj-strong-ge60_e32756.cpg
sl8olre_p089r082_d2025082620260109_dlj-dlj-strong-ge60_e32756.dbf
sl8olre_p089r082_d2025082620260109_dlj-dlj-strong-ge60_e32756.prj
sl8olre_p089r082_d2025082620260109_dlj-dlj-strong-ge60_e32756.shp
sl8olre_p089r082_d2025082620260109_dlj-dlj-strong-ge60_e32756.shx
sl8olre_p089r082_d2025082620260109_dlj-dlj-strong-ge60_e32756.tif
sl8olre_p089r082_d2025082620260109_dlj_e32756.tif
sl9olre_p089r082_20250826_ga0_e32756.tif

--- p089r083 ---
sl8olre_p089r083_20260109_ga0_e32756.tif
sl8olre_p089r083_d2025091120260109_dlj-dlj-clear-ge80_e32756.cpg
sl8olre_p089r083_d2025091120260109_dlj-dlj-clear-ge80_e32756.dbf
sl8olre_p089r083_d2025091120260109_dlj-dlj-clear-ge80_e32756.prj
sl8olre_p089r083_d2025091120260109_dlj-dlj-clear-ge80_e32756.shp
sl8olre_p089r083_d2025091120260109_dlj-dlj-clear-ge80_e32756.shx
sl8olre_p089r083_d2025091120260109_dlj-dlj-clear-ge80_e32756.tif
sl8olre_p089r083_d2025091120260109_dlj-dlj-strong-ge60_e32756.cpg
sl8olre_p089r083_d2025091120260109_dlj-dlj-strong-ge60_e32756.dbf
sl8olre_p089r083_d2025091120260109_dlj-dlj-strong-ge60_e32756.prj
sl8olre_p089r083_d2025091120260109_dlj-dlj-strong-ge60_e32756.shp
sl8olre_p089r083_d2025091120260109_dlj-dlj-strong-ge60_e32756.shx
sl8olre_p089r083_d2025091120260109_dlj-dlj-strong-ge60_e32756.tif
sl8olre_p089r083_d2025091120260109_dlj_e32756.tif
sl9olre_p089r083_20250911_ga0_e32756.tif

--- p089r084 ---
sl8olre_p089r084_20260109_ga0_e32756.tif
sl8olre_p089r084_d2025091120260109_dlj-dlj-clear-ge80_e32756.cpg
sl8olre_p089r084_d2025091120260109_dlj-dlj-clear-ge80_e32756.dbf
sl8olre_p089r084_d2025091120260109_dlj-dlj-clear-ge80_e32756.prj
sl8olre_p089r084_d2025091120260109_dlj-dlj-clear-ge80_e32756.shp
sl8olre_p089r084_d2025091120260109_dlj-dlj-clear-ge80_e32756.shx
sl8olre_p089r084_d2025091120260109_dlj-dlj-clear-ge80_e32756.tif
sl8olre_p089r084_d2025091120260109_dlj-dlj-strong-ge60_e32756.cpg
sl8olre_p089r084_d2025091120260109_dlj-dlj-strong-ge60_e32756.dbf
sl8olre_p089r084_d2025091120260109_dlj-dlj-strong-ge60_e32756.prj
sl8olre_p089r084_d2025091120260109_dlj-dlj-strong-ge60_e32756.shp
sl8olre_p089r084_d2025091120260109_dlj-dlj-strong-ge60_e32756.shx
sl8olre_p089r084_d2025091120260109_dlj-dlj-strong-ge60_e32756.tif
sl8olre_p089r084_d2025091120260109_dlj_e32756.tif
sl9olre_p089r084_20250911_ga0_e32756.tif

--- p090r077 ---
sl9olre_p090r077_20250817_ga0_e32756.tif
sl9olre_p090r077_20260108_ga0_e32756.tif
sl9olre_p090r077_d2025081720260108_dlj-dlj-clear-ge80_e32756.cpg
sl9olre_p090r077_d2025081720260108_dlj-dlj-clear-ge80_e32756.dbf
sl9olre_p090r077_d2025081720260108_dlj-dlj-clear-ge80_e32756.prj
sl9olre_p090r077_d2025081720260108_dlj-dlj-clear-ge80_e32756.shp
sl9olre_p090r077_d2025081720260108_dlj-dlj-clear-ge80_e32756.shx
sl9olre_p090r077_d2025081720260108_dlj-dlj-clear-ge80_e32756.tif
sl9olre_p090r077_d2025081720260108_dlj-dlj-strong-ge60_e32756.cpg
sl9olre_p090r077_d2025081720260108_dlj-dlj-strong-ge60_e32756.dbf
sl9olre_p090r077_d2025081720260108_dlj-dlj-strong-ge60_e32756.prj
sl9olre_p090r077_d2025081720260108_dlj-dlj-strong-ge60_e32756.shp
sl9olre_p090r077_d2025081720260108_dlj-dlj-strong-ge60_e32756.shx
sl9olre_p090r077_d2025081720260108_dlj-dlj-strong-ge60_e32756.tif
sl9olre_p090r077_d2025081720260108_dlj_e32756.tif

--- p090r078 ---
sl8olre_p090r078_20250910_ga0_e32756.tif
sl9olre_p090r078_20251207_ga0_e32756.tif
sl9olre_p090r078_d2025091020251207_dlj-dlj-clear-ge80_e32756.cpg
sl9olre_p090r078_d2025091020251207_dlj-dlj-clear-ge80_e32756.dbf
sl9olre_p090r078_d2025091020251207_dlj-dlj-clear-ge80_e32756.prj
sl9olre_p090r078_d2025091020251207_dlj-dlj-clear-ge80_e32756.shp
sl9olre_p090r078_d2025091020251207_dlj-dlj-clear-ge80_e32756.shx
sl9olre_p090r078_d2025091020251207_dlj-dlj-clear-ge80_e32756.tif
sl9olre_p090r078_d2025091020251207_dlj-dlj-strong-ge60_e32756.cpg
sl9olre_p090r078_d2025091020251207_dlj-dlj-strong-ge60_e32756.dbf
sl9olre_p090r078_d2025091020251207_dlj-dlj-strong-ge60_e32756.prj
sl9olre_p090r078_d2025091020251207_dlj-dlj-strong-ge60_e32756.shp
sl9olre_p090r078_d2025091020251207_dlj-dlj-strong-ge60_e32756.shx
sl9olre_p090r078_d2025091020251207_dlj-dlj-strong-ge60_e32756.tif
sl9olre_p090r078_d2025091020251207_dlj_e32756.tif

--- p090r079 ---
sl8olre_p090r079_20251231_ga0_e32756.tif
sl8olre_p090r079_d2025100420251231_dlj-dlj-clear-ge80_e32756.cpg
sl8olre_p090r079_d2025100420251231_dlj-dlj-clear-ge80_e32756.dbf
sl8olre_p090r079_d2025100420251231_dlj-dlj-clear-ge80_e32756.prj
sl8olre_p090r079_d2025100420251231_dlj-dlj-clear-ge80_e32756.shp
sl8olre_p090r079_d2025100420251231_dlj-dlj-clear-ge80_e32756.shx
sl8olre_p090r079_d2025100420251231_dlj-dlj-clear-ge80_e32756.tif
sl8olre_p090r079_d2025100420251231_dlj-dlj-strong-ge60_e32756.cpg
sl8olre_p090r079_d2025100420251231_dlj-dlj-strong-ge60_e32756.dbf
sl8olre_p090r079_d2025100420251231_dlj-dlj-strong-ge60_e32756.prj
sl8olre_p090r079_d2025100420251231_dlj-dlj-strong-ge60_e32756.shp
sl8olre_p090r079_d2025100420251231_dlj-dlj-strong-ge60_e32756.shx
sl8olre_p090r079_d2025100420251231_dlj-dlj-strong-ge60_e32756.tif
sl8olre_p090r079_d2025100420251231_dlj_e32756.tif
sl9olre_p090r079_20251004_ga0_e32756.tif

--- p090r080 ---
sl9olre_p090r080_20251004_ga0_e32756.tif
sl9olre_p090r080_20260108_ga0_e32756.tif
sl9olre_p090r080_d2025100420260108_dlj-dlj-clear-ge80_e32756.cpg
sl9olre_p090r080_d2025100420260108_dlj-dlj-clear-ge80_e32756.dbf
sl9olre_p090r080_d2025100420260108_dlj-dlj-clear-ge80_e32756.prj
sl9olre_p090r080_d2025100420260108_dlj-dlj-clear-ge80_e32756.shp
sl9olre_p090r080_d2025100420260108_dlj-dlj-clear-ge80_e32756.shx
sl9olre_p090r080_d2025100420260108_dlj-dlj-clear-ge80_e32756.tif
sl9olre_p090r080_d2025100420260108_dlj-dlj-strong-ge60_e32756.cpg
sl9olre_p090r080_d2025100420260108_dlj-dlj-strong-ge60_e32756.dbf
sl9olre_p090r080_d2025100420260108_dlj-dlj-strong-ge60_e32756.prj
sl9olre_p090r080_d2025100420260108_dlj-dlj-strong-ge60_e32756.shp
sl9olre_p090r080_d2025100420260108_dlj-dlj-strong-ge60_e32756.shx
sl9olre_p090r080_d2025100420260108_dlj-dlj-strong-ge60_e32756.tif
sl9olre_p090r080_d2025100420260108_dlj_e32756.tif

--- p090r081 ---
sl9olre_p090r081_20251105_ga0_e32756.tif
sl9olre_p090r081_20260108_ga0_e32756.tif
sl9olre_p090r081_d2025110520260108_dlj-dlj-clear-ge80_e32756.cpg
sl9olre_p090r081_d2025110520260108_dlj-dlj-clear-ge80_e32756.dbf
sl9olre_p090r081_d2025110520260108_dlj-dlj-clear-ge80_e32756.prj
sl9olre_p090r081_d2025110520260108_dlj-dlj-clear-ge80_e32756.shp
sl9olre_p090r081_d2025110520260108_dlj-dlj-clear-ge80_e32756.shx
sl9olre_p090r081_d2025110520260108_dlj-dlj-clear-ge80_e32756.tif
sl9olre_p090r081_d2025110520260108_dlj-dlj-strong-ge60_e32756.cpg
sl9olre_p090r081_d2025110520260108_dlj-dlj-strong-ge60_e32756.dbf
sl9olre_p090r081_d2025110520260108_dlj-dlj-strong-ge60_e32756.prj
sl9olre_p090r081_d2025110520260108_dlj-dlj-strong-ge60_e32756.shp
sl9olre_p090r081_d2025110520260108_dlj-dlj-strong-ge60_e32756.shx
sl9olre_p090r081_d2025110520260108_dlj-dlj-strong-ge60_e32756.tif
sl9olre_p090r081_d2025110520260108_dlj_e32756.tif

--- p090r082 ---
sl9olre_p090r082_20251105_ga0_e32756.tif
sl9olre_p090r082_20260108_ga0_e32756.tif
sl9olre_p090r082_d2025110520260108_dlj-dlj-clear-ge80_e32756.cpg
sl9olre_p090r082_d2025110520260108_dlj-dlj-clear-ge80_e32756.dbf
sl9olre_p090r082_d2025110520260108_dlj-dlj-clear-ge80_e32756.prj
sl9olre_p090r082_d2025110520260108_dlj-dlj-clear-ge80_e32756.shp
sl9olre_p090r082_d2025110520260108_dlj-dlj-clear-ge80_e32756.shx
sl9olre_p090r082_d2025110520260108_dlj-dlj-clear-ge80_e32756.tif
sl9olre_p090r082_d2025110520260108_dlj-dlj-strong-ge60_e32756.cpg
sl9olre_p090r082_d2025110520260108_dlj-dlj-strong-ge60_e32756.dbf
sl9olre_p090r082_d2025110520260108_dlj-dlj-strong-ge60_e32756.prj
sl9olre_p090r082_d2025110520260108_dlj-dlj-strong-ge60_e32756.shp
sl9olre_p090r082_d2025110520260108_dlj-dlj-strong-ge60_e32756.shx
sl9olre_p090r082_d2025110520260108_dlj-dlj-strong-ge60_e32756.tif
sl9olre_p090r082_d2025110520260108_dlj_e32756.tif

--- p090r083 ---
sl8olre_p090r083_20250708_ga0_e32756.tif
sl9olre_p090r083_20260108_ga0_e32756.tif
sl9olre_p090r083_d2025070820260108_dlj-dlj-clear-ge80_e32756.cpg
sl9olre_p090r083_d2025070820260108_dlj-dlj-clear-ge80_e32756.dbf
sl9olre_p090r083_d2025070820260108_dlj-dlj-clear-ge80_e32756.prj
sl9olre_p090r083_d2025070820260108_dlj-dlj-clear-ge80_e32756.shp
sl9olre_p090r083_d2025070820260108_dlj-dlj-clear-ge80_e32756.shx
sl9olre_p090r083_d2025070820260108_dlj-dlj-clear-ge80_e32756.tif
sl9olre_p090r083_d2025070820260108_dlj-dlj-strong-ge60_e32756.cpg
sl9olre_p090r083_d2025070820260108_dlj-dlj-strong-ge60_e32756.dbf
sl9olre_p090r083_d2025070820260108_dlj-dlj-strong-ge60_e32756.prj
sl9olre_p090r083_d2025070820260108_dlj-dlj-strong-ge60_e32756.shp
sl9olre_p090r083_d2025070820260108_dlj-dlj-strong-ge60_e32756.shx
sl9olre_p090r083_d2025070820260108_dlj-dlj-strong-ge60_e32756.tif
sl9olre_p090r083_d2025070820260108_dlj_e32756.tif

--- p090r084 ---
sl9olre_p090r084_20251105_ga0_e32755.tif
sl9olre_p090r084_20260108_ga0_e32755.tif
sl9olre_p090r084_d2025110520260108_dlj-dlj-clear-ge80_e32755.cpg
sl9olre_p090r084_d2025110520260108_dlj-dlj-clear-ge80_e32755.dbf
sl9olre_p090r084_d2025110520260108_dlj-dlj-clear-ge80_e32755.prj
sl9olre_p090r084_d2025110520260108_dlj-dlj-clear-ge80_e32755.shp
sl9olre_p090r084_d2025110520260108_dlj-dlj-clear-ge80_e32755.shx
sl9olre_p090r084_d2025110520260108_dlj-dlj-clear-ge80_e32755.tif
sl9olre_p090r084_d2025110520260108_dlj-dlj-strong-ge60_e32755.cpg
sl9olre_p090r084_d2025110520260108_dlj-dlj-strong-ge60_e32755.dbf
sl9olre_p090r084_d2025110520260108_dlj-dlj-strong-ge60_e32755.prj
sl9olre_p090r084_d2025110520260108_dlj-dlj-strong-ge60_e32755.shp
sl9olre_p090r084_d2025110520260108_dlj-dlj-strong-ge60_e32755.shx
sl9olre_p090r084_d2025110520260108_dlj-dlj-strong-ge60_e32755.tif
sl9olre_p090r084_d2025110520260108_dlj_e32755.tif

--- p090r085 ---
sl9olre_p090r085_20250918_ga0_e32755.tif
sl9olre_p090r085_20260108_ga0_e32755.tif
sl9olre_p090r085_d2025091820260108_dlj-dlj-clear-ge80_e32755.cpg
sl9olre_p090r085_d2025091820260108_dlj-dlj-clear-ge80_e32755.dbf
sl9olre_p090r085_d2025091820260108_dlj-dlj-clear-ge80_e32755.prj
sl9olre_p090r085_d2025091820260108_dlj-dlj-clear-ge80_e32755.shp
sl9olre_p090r085_d2025091820260108_dlj-dlj-clear-ge80_e32755.shx
sl9olre_p090r085_d2025091820260108_dlj-dlj-clear-ge80_e32755.tif
sl9olre_p090r085_d2025091820260108_dlj-dlj-strong-ge60_e32755.cpg
sl9olre_p090r085_d2025091820260108_dlj-dlj-strong-ge60_e32755.dbf
sl9olre_p090r085_d2025091820260108_dlj-dlj-strong-ge60_e32755.prj
sl9olre_p090r085_d2025091820260108_dlj-dlj-strong-ge60_e32755.shp
sl9olre_p090r085_d2025091820260108_dlj-dlj-strong-ge60_e32755.shx
sl9olre_p090r085_d2025091820260108_dlj-dlj-strong-ge60_e32755.tif
sl9olre_p090r085_d2025091820260108_dlj_e32755.tif

--- p090r086 ---
sl9olre_p090r086_20251105_ga0_e32755.tif
sl9olre_p090r086_20251223_ga0_e32755.tif
sl9olre_p090r086_d2025110520251223_dlj-dlj-clear-ge80_e32755.cpg
sl9olre_p090r086_d2025110520251223_dlj-dlj-clear-ge80_e32755.dbf
sl9olre_p090r086_d2025110520251223_dlj-dlj-clear-ge80_e32755.prj
sl9olre_p090r086_d2025110520251223_dlj-dlj-clear-ge80_e32755.shp
sl9olre_p090r086_d2025110520251223_dlj-dlj-clear-ge80_e32755.shx
sl9olre_p090r086_d2025110520251223_dlj-dlj-clear-ge80_e32755.tif
sl9olre_p090r086_d2025110520251223_dlj-dlj-strong-ge60_e32755.cpg
sl9olre_p090r086_d2025110520251223_dlj-dlj-strong-ge60_e32755.dbf
sl9olre_p090r086_d2025110520251223_dlj-dlj-strong-ge60_e32755.prj
sl9olre_p090r086_d2025110520251223_dlj-dlj-strong-ge60_e32755.shp
sl9olre_p090r086_d2025110520251223_dlj-dlj-strong-ge60_e32755.shx
sl9olre_p090r086_d2025110520251223_dlj-dlj-strong-ge60_e32755.tif
sl9olre_p090r086_d2025110520251223_dlj_e32755.tif

--- p090r088 ---
sl8olre_p090r088_20251012_ga0_e32755.tif
sl8olre_p090r088_20251231_ga0_e32755.tif
sl8olre_p090r088_d2025101220251231_dlj-dlj-clear-ge80_e32755.cpg
sl8olre_p090r088_d2025101220251231_dlj-dlj-clear-ge80_e32755.dbf
sl8olre_p090r088_d2025101220251231_dlj-dlj-clear-ge80_e32755.prj
sl8olre_p090r088_d2025101220251231_dlj-dlj-clear-ge80_e32755.shp
sl8olre_p090r088_d2025101220251231_dlj-dlj-clear-ge80_e32755.shx
sl8olre_p090r088_d2025101220251231_dlj-dlj-clear-ge80_e32755.tif
sl8olre_p090r088_d2025101220251231_dlj-dlj-strong-ge60_e32755.cpg
sl8olre_p090r088_d2025101220251231_dlj-dlj-strong-ge60_e32755.dbf
sl8olre_p090r088_d2025101220251231_dlj-dlj-strong-ge60_e32755.prj
sl8olre_p090r088_d2025101220251231_dlj-dlj-strong-ge60_e32755.shp
sl8olre_p090r088_d2025101220251231_dlj-dlj-strong-ge60_e32755.shx
sl8olre_p090r088_d2025101220251231_dlj-dlj-strong-ge60_e32755.tif
sl8olre_p090r088_d2025101220251231_dlj_e32755.tif

--- p090r089 ---
sl8olre_p090r089_20251012_ga0_e32755.tif
sl8olre_p090r089_20251231_ga0_e32755.tif
sl8olre_p090r089_d2025101220251231_dlj-dlj-clear-ge80_e32755.cpg
sl8olre_p090r089_d2025101220251231_dlj-dlj-clear-ge80_e32755.dbf
sl8olre_p090r089_d2025101220251231_dlj-dlj-clear-ge80_e32755.prj
sl8olre_p090r089_d2025101220251231_dlj-dlj-clear-ge80_e32755.shp
sl8olre_p090r089_d2025101220251231_dlj-dlj-clear-ge80_e32755.shx
sl8olre_p090r089_d2025101220251231_dlj-dlj-clear-ge80_e32755.tif

# Export and zip

In [6]:
from pathlib import Path

export_dir = Path("/home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles")
export_dir.mkdir(parents=True, exist_ok=True)

export_dir

PosixPath('/home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles')

In [7]:
row = eds_df.iloc[0]

print("bucket:", bucket)
print("key:", repr(row["key"]))

bucket: dcceew-eds-data
key: 'AROAZ6PFZYT4B4C7MNRHV:robotmcgregor/eds/tiles/p089r078/2025/20250701/sl8olre_p089r078_20250701_ga0_e32756.tif'

In [8]:
client.head_object(Bucket=bucket, Key=row["key"])

{'ResponseMetadata': {'RequestId': '1GDTZAW9Z9RW70Z0',
  'HostId': '3qsMkSyuTGNR71skNp9/TcD0bKd4SrxOeT+TcnTW2yBilaXw7o3PpgABAuGRlYYdedM0IGFmg5czminpuhPa2iYAVOPD0cUX',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': '3qsMkSyuTGNR71skNp9/TcD0bKd4SrxOeT+TcnTW2yBilaXw7o3PpgABAuGRlYYdedM0IGFmg5czminpuhPa2iYAVOPD0cUX',
   'x-amz-request-id': '1GDTZAW9Z9RW70Z0',
   'date': 'Mon, 20 Apr 2026 06:47:16 GMT',
   'last-modified': 'Mon, 20 Apr 2026 03:38:01 GMT',
   'etag': '"4d5164ecce6ab4dff65f28fb4f4d16e1-44"',
   'x-amz-server-side-encryption': 'AES256',
   'x-amz-version-id': 'null',
   'accept-ranges': 'bytes',
   'content-type': 'binary/octet-stream',
   'content-length': '366298854',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'AcceptRanges': 'bytes',
 'LastModified': datetime.datetime(2026, 4, 20, 3, 38, 1, tzinfo=tzutc()),
 'ContentLength': 366298854,
 'ETag': '"4d5164ecce6ab4dff65f28fb4f4d16e1-44"',
 'VersionId': 'null',
 'ContentType': 'binary/octet-stream',
 'ServerSideEncryption': 'AES256',
 'Metadata': {}}

In [9]:
import re
import shutil
from pathlib import Path
from zipfile import ZipFile, ZIP_DEFLATED

# Settings
delete_unzipped_files = False   # True = delete files after successful zipping

print(f"Output directory: {export_dir.resolve()}")


def extract_date_group(filename: str) -> str:
    """
    Extract a grouping token from filename.

    Examples:
    - sl8olre_p089r078_20250701_ga0_e32756.tif
      -> 20250701

    - sl8olre_p089r078_d2025070120251208_dlj_e32756.tif
      -> d2025070120251208
    """
    # Match date ranges first, e.g. d2025070120251208
    m = re.search(r'(d\d{16})', filename)
    if m:
        return m.group(1)

    # Then match single dates, e.g. 20250701
    m = re.search(r'(?<!\d)(\d{8})(?!\d)', filename)
    if m:
        return m.group(1)

    return "unknown"


for tile, group in eds_df.groupby("tile"):

    tile_dir = export_dir / tile
    tile_dir.mkdir(parents=True, exist_ok=True)

    print(f"\nDownloading {tile}")
    print(f"Tile folder: {tile_dir.resolve()}")

    downloaded_files = []

    for _, row in group.iterrows():
        key = row["key"]
        local_path = tile_dir / row["file"]

        client.download_file(bucket, key, str(local_path))
        downloaded_files.append(local_path)

        print("  downloaded:", local_path.name)

    # Group downloaded files by extracted date token
    files_by_group = {}

    for file_path in downloaded_files:
        group_key = extract_date_group(file_path.name)
        files_by_group.setdefault(group_key, []).append(file_path)

    print(f"\nCreating split ZIPs for {tile}")

    for group_key, file_list in sorted(files_by_group.items()):
        zip_path = export_dir / f"{tile}_{group_key}.zip"
        print(f"  creating: {zip_path.resolve()}")

        with ZipFile(zip_path, "w", compression=ZIP_DEFLATED) as zipf:
            for file_path in file_list:
                # Store file inside zip with just its filename
                zipf.write(file_path, arcname=file_path.name)

        print(f"  zipped: {zip_path.name} ({len(file_list)} files)")

    # Optionally delete originals after all ZIPs are created
    if delete_unzipped_files:
        shutil.rmtree(tile_dir)
        print(f"  deleted folder: {tile_dir}")

Output directory: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles

Downloading p089r078
Tile folder: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r078
  downloaded: sl8olre_p089r078_20250701_ga0_e32756.tif
  downloaded: sl8olre_p089r078_20251208_ga0_e32756.tif
  downloaded: sl9olre_p089r078_20260117_ga0_e32756.tif
  downloaded: sl8olre_p089r078_d2025070120251208_dlj-dlj-clear-ge80_e32756.tif
  downloaded: sl8olre_p089r078_d2025070120251208_dlj-dlj-strong-ge60_e32756.tif
  downloaded: sl9olre_p089r078_d2025070120260117_dlj-dlj-clear-ge80_e32756.tif
  downloaded: sl9olre_p089r078_d2025070120260117_dlj-dlj-strong-ge60_e32756.tif
  downloaded: sl8olre_p089r078_d2025070120251208_dlj_e32756.tif
  downloaded: sl9olre_p089r078_d2025070120260117_dlj_e32756.tif
  downloaded: sl8olre_p089r078_d2025070120251208_dlj-dlj-clear-ge80_e32756.cpg
  downloaded: sl8olre_p089r078_d2025070120251208_dlj-dlj-clear-ge80_e32756.dbf
  downloaded: sl8olre_p089r078_d2025070120251208_dlj-dlj-clear-ge80_e32756.prj
  downloaded: sl8olre_p089r078_d2025070120251208_dlj-dlj-clear-ge80_e32756.shp
  downloaded: sl8olre_p089r078_d2025070120251208_dlj-dlj-clear-ge80_e32756.shx
  downloaded: sl9olre_p089r078_d2025070120260117_dlj-dlj-clear-ge80_e32756.cpg
  downloaded: sl9olre_p089r078_d2025070120260117_dlj-dlj-clear-ge80_e32756.dbf
  downloaded: sl9olre_p089r078_d2025070120260117_dlj-dlj-clear-ge80_e32756.prj
  downloaded: sl9olre_p089r078_d2025070120260117_dlj-dlj-clear-ge80_e32756.shp
  downloaded: sl9olre_p089r078_d2025070120260117_dlj-dlj-clear-ge80_e32756.shx
  downloaded: sl8olre_p089r078_d2025070120251208_dlj-dlj-strong-ge60_e32756.cpg
  downloaded: sl8olre_p089r078_d2025070120251208_dlj-dlj-strong-ge60_e32756.dbf
  downloaded: sl8olre_p089r078_d2025070120251208_dlj-dlj-strong-ge60_e32756.prj
  downloaded: sl8olre_p089r078_d2025070120251208_dlj-dlj-strong-ge60_e32756.shp
  downloaded: sl8olre_p089r078_d2025070120251208_dlj-dlj-strong-ge60_e32756.shx
  downloaded: sl9olre_p089r078_d2025070120260117_dlj-dlj-strong-ge60_e32756.cpg
  downloaded: sl9olre_p089r078_d2025070120260117_dlj-dlj-strong-ge60_e32756.dbf
  downloaded: sl9olre_p089r078_d2025070120260117_dlj-dlj-strong-ge60_e32756.prj
  downloaded: sl9olre_p089r078_d2025070120260117_dlj-dlj-strong-ge60_e32756.shp
  downloaded: sl9olre_p089r078_d2025070120260117_dlj-dlj-strong-ge60_e32756.shx

Creating split ZIPs for p089r078
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r078_20250701.zip
  zipped: p089r078_20250701.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r078_20251208.zip
  zipped: p089r078_20251208.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r078_20260117.zip
  zipped: p089r078_20260117.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r078_d2025070120251208.zip
  zipped: p089r078_d2025070120251208.zip (13 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r078_d2025070120260117.zip
  zipped: p089r078_d2025070120260117.zip (13 files)

Downloading p089r079
Tile folder: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r079
  downloaded: sl9olre_p089r079_20250607_ga0_e32756.tif
  downloaded: sl8olre_p089r079_20260109_ga0_e32756.tif
  downloaded: sl8olre_p089r079_20260125_ga0_e32756.tif
  downloaded: sl8olre_p089r079_d2025060720260109_dlj-dlj-clear-ge80_e32756.tif
  downloaded: sl8olre_p089r079_d2025060720260109_dlj-dlj-strong-ge60_e32756.tif
  downloaded: sl8olre_p089r079_d2025060720260125_dlj-dlj-clear-ge80_e32756.tif
  downloaded: sl8olre_p089r079_d2025060720260125_dlj-dlj-strong-ge60_e32756.tif
  downloaded: sl8olre_p089r079_d2025060720260109_dlj_e32756.tif
  downloaded: sl8olre_p089r079_d2025060720260125_dlj_e32756.tif
  downloaded: sl8olre_p089r079_d2025060720260109_dlj-dlj-clear-ge80_e32756.cpg
  downloaded: sl8olre_p089r079_d2025060720260109_dlj-dlj-clear-ge80_e32756.dbf
  downloaded: sl8olre_p089r079_d2025060720260109_dlj-dlj-clear-ge80_e32756.prj
  downloaded: sl8olre_p089r079_d2025060720260109_dlj-dlj-clear-ge80_e32756.shp
  downloaded: sl8olre_p089r079_d2025060720260109_dlj-dlj-clear-ge80_e32756.shx
  downloaded: sl8olre_p089r079_d2025060720260125_dlj-dlj-clear-ge80_e32756.cpg
  downloaded: sl8olre_p089r079_d2025060720260125_dlj-dlj-clear-ge80_e32756.dbf
  downloaded: sl8olre_p089r079_d2025060720260125_dlj-dlj-clear-ge80_e32756.prj
  downloaded: sl8olre_p089r079_d2025060720260125_dlj-dlj-clear-ge80_e32756.shp
  downloaded: sl8olre_p089r079_d2025060720260125_dlj-dlj-clear-ge80_e32756.shx
  downloaded: sl8olre_p089r079_d2025060720260109_dlj-dlj-strong-ge60_e32756.cpg
  downloaded: sl8olre_p089r079_d2025060720260109_dlj-dlj-strong-ge60_e32756.dbf
  downloaded: sl8olre_p089r079_d2025060720260109_dlj-dlj-strong-ge60_e32756.prj
  downloaded: sl8olre_p089r079_d2025060720260109_dlj-dlj-strong-ge60_e32756.shp
  downloaded: sl8olre_p089r079_d2025060720260109_dlj-dlj-strong-ge60_e32756.shx
  downloaded: sl8olre_p089r079_d2025060720260125_dlj-dlj-strong-ge60_e32756.cpg
  downloaded: sl8olre_p089r079_d2025060720260125_dlj-dlj-strong-ge60_e32756.dbf
  downloaded: sl8olre_p089r079_d2025060720260125_dlj-dlj-strong-ge60_e32756.prj
  downloaded: sl8olre_p089r079_d2025060720260125_dlj-dlj-strong-ge60_e32756.shp
  downloaded: sl8olre_p089r079_d2025060720260125_dlj-dlj-strong-ge60_e32756.shx

Creating split ZIPs for p089r079
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r079_20250607.zip
  zipped: p089r079_20250607.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r079_20260109.zip
  zipped: p089r079_20260109.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r079_20260125.zip
  zipped: p089r079_20260125.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r079_d2025060720260109.zip
  zipped: p089r079_d2025060720260109.zip (13 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r079_d2025060720260125.zip
  zipped: p089r079_d2025060720260125.zip (13 files)

Downloading p089r080
Tile folder: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r080
  downloaded: sl9olre_p089r080_20250607_ga0_e32756.tif
  downloaded: sl8olre_p089r080_20260109_ga0_e32756.tif
  downloaded: sl8olre_p089r080_20260125_ga0_e32756.tif
  downloaded: sl8olre_p089r080_d2025060720260109_dlj-dlj-clear-ge80_e32756.tif
  downloaded: sl8olre_p089r080_d2025060720260109_dlj-dlj-strong-ge60_e32756.tif
  downloaded: sl8olre_p089r080_d2025060720260125_dlj-dlj-clear-ge80_e32756.tif
  downloaded: sl8olre_p089r080_d2025060720260125_dlj-dlj-strong-ge60_e32756.tif
  downloaded: sl8olre_p089r080_d2025060720260109_dlj_e32756.tif
  downloaded: sl8olre_p089r080_d2025060720260125_dlj_e32756.tif
  downloaded: sl8olre_p089r080_d2025060720260109_dlj-dlj-clear-ge80_e32756.cpg
  downloaded: sl8olre_p089r080_d2025060720260109_dlj-dlj-clear-ge80_e32756.dbf
  downloaded: sl8olre_p089r080_d2025060720260109_dlj-dlj-clear-ge80_e32756.prj
  downloaded: sl8olre_p089r080_d2025060720260109_dlj-dlj-clear-ge80_e32756.shp
  downloaded: sl8olre_p089r080_d2025060720260109_dlj-dlj-clear-ge80_e32756.shx
  downloaded: sl8olre_p089r080_d2025060720260125_dlj-dlj-clear-ge80_e32756.cpg
  downloaded: sl8olre_p089r080_d2025060720260125_dlj-dlj-clear-ge80_e32756.dbf
  downloaded: sl8olre_p089r080_d2025060720260125_dlj-dlj-clear-ge80_e32756.prj
  downloaded: sl8olre_p089r080_d2025060720260125_dlj-dlj-clear-ge80_e32756.shp
  downloaded: sl8olre_p089r080_d2025060720260125_dlj-dlj-clear-ge80_e32756.shx
  downloaded: sl8olre_p089r080_d2025060720260109_dlj-dlj-strong-ge60_e32756.cpg
  downloaded: sl8olre_p089r080_d2025060720260109_dlj-dlj-strong-ge60_e32756.dbf
  downloaded: sl8olre_p089r080_d2025060720260109_dlj-dlj-strong-ge60_e32756.prj
  downloaded: sl8olre_p089r080_d2025060720260109_dlj-dlj-strong-ge60_e32756.shp
  downloaded: sl8olre_p089r080_d2025060720260109_dlj-dlj-strong-ge60_e32756.shx
  downloaded: sl8olre_p089r080_d2025060720260125_dlj-dlj-strong-ge60_e32756.cpg
  downloaded: sl8olre_p089r080_d2025060720260125_dlj-dlj-strong-ge60_e32756.dbf
  downloaded: sl8olre_p089r080_d2025060720260125_dlj-dlj-strong-ge60_e32756.prj
  downloaded: sl8olre_p089r080_d2025060720260125_dlj-dlj-strong-ge60_e32756.shp
  downloaded: sl8olre_p089r080_d2025060720260125_dlj-dlj-strong-ge60_e32756.shx

Creating split ZIPs for p089r080
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r080_20250607.zip
  zipped: p089r080_20250607.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r080_20260109.zip
  zipped: p089r080_20260109.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r080_20260125.zip
  zipped: p089r080_20260125.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r080_d2025060720260109.zip
  zipped: p089r080_d2025060720260109.zip (13 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r080_d2025060720260125.zip
  zipped: p089r080_d2025060720260125.zip (13 files)

Downloading p089r081
Tile folder: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r081
  downloaded: sl9olre_p089r081_20250826_ga0_e32756.tif
  downloaded: sl8olre_p089r081_20260109_ga0_e32756.tif
  downloaded: sl8olre_p089r081_d2025082620260109_dlj-dlj-clear-ge80_e32756.tif
  downloaded: sl8olre_p089r081_d2025082620260109_dlj-dlj-strong-ge60_e32756.tif
  downloaded: sl8olre_p089r081_d2025082620260109_dlj_e32756.tif
  downloaded: sl8olre_p089r081_d2025082620260109_dlj-dlj-clear-ge80_e32756.cpg
  downloaded: sl8olre_p089r081_d2025082620260109_dlj-dlj-clear-ge80_e32756.dbf
  downloaded: sl8olre_p089r081_d2025082620260109_dlj-dlj-clear-ge80_e32756.prj
  downloaded: sl8olre_p089r081_d2025082620260109_dlj-dlj-clear-ge80_e32756.shp
  downloaded: sl8olre_p089r081_d2025082620260109_dlj-dlj-clear-ge80_e32756.shx
  downloaded: sl8olre_p089r081_d2025082620260109_dlj-dlj-strong-ge60_e32756.cpg
  downloaded: sl8olre_p089r081_d2025082620260109_dlj-dlj-strong-ge60_e32756.dbf
  downloaded: sl8olre_p089r081_d2025082620260109_dlj-dlj-strong-ge60_e32756.prj
  downloaded: sl8olre_p089r081_d2025082620260109_dlj-dlj-strong-ge60_e32756.shp
  downloaded: sl8olre_p089r081_d2025082620260109_dlj-dlj-strong-ge60_e32756.shx

Creating split ZIPs for p089r081
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r081_20250826.zip
  zipped: p089r081_20250826.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r081_20260109.zip
  zipped: p089r081_20260109.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r081_d2025082620260109.zip
  zipped: p089r081_d2025082620260109.zip (13 files)

Downloading p089r082
Tile folder: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r082
  downloaded: sl9olre_p089r082_20250826_ga0_e32756.tif
  downloaded: sl8olre_p089r082_20260109_ga0_e32756.tif
  downloaded: sl8olre_p089r082_d2025082620260109_dlj-dlj-clear-ge80_e32756.tif
  downloaded: sl8olre_p089r082_d2025082620260109_dlj-dlj-strong-ge60_e32756.tif
  downloaded: sl8olre_p089r082_d2025082620260109_dlj_e32756.tif
  downloaded: sl8olre_p089r082_d2025082620260109_dlj-dlj-clear-ge80_e32756.cpg
  downloaded: sl8olre_p089r082_d2025082620260109_dlj-dlj-clear-ge80_e32756.dbf
  downloaded: sl8olre_p089r082_d2025082620260109_dlj-dlj-clear-ge80_e32756.prj
  downloaded: sl8olre_p089r082_d2025082620260109_dlj-dlj-clear-ge80_e32756.shp
  downloaded: sl8olre_p089r082_d2025082620260109_dlj-dlj-clear-ge80_e32756.shx
  downloaded: sl8olre_p089r082_d2025082620260109_dlj-dlj-strong-ge60_e32756.cpg
  downloaded: sl8olre_p089r082_d2025082620260109_dlj-dlj-strong-ge60_e32756.dbf
  downloaded: sl8olre_p089r082_d2025082620260109_dlj-dlj-strong-ge60_e32756.prj
  downloaded: sl8olre_p089r082_d2025082620260109_dlj-dlj-strong-ge60_e32756.shp
  downloaded: sl8olre_p089r082_d2025082620260109_dlj-dlj-strong-ge60_e32756.shx

Creating split ZIPs for p089r082
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r082_20250826.zip
  zipped: p089r082_20250826.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r082_20260109.zip
  zipped: p089r082_20260109.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r082_d2025082620260109.zip
  zipped: p089r082_d2025082620260109.zip (13 files)

Downloading p089r083
Tile folder: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r083
  downloaded: sl9olre_p089r083_20250911_ga0_e32756.tif
  downloaded: sl8olre_p089r083_20260109_ga0_e32756.tif
  downloaded: sl8olre_p089r083_d2025091120260109_dlj-dlj-clear-ge80_e32756.tif
  downloaded: sl8olre_p089r083_d2025091120260109_dlj-dlj-strong-ge60_e32756.tif
  downloaded: sl8olre_p089r083_d2025091120260109_dlj_e32756.tif
  downloaded: sl8olre_p089r083_d2025091120260109_dlj-dlj-clear-ge80_e32756.cpg
  downloaded: sl8olre_p089r083_d2025091120260109_dlj-dlj-clear-ge80_e32756.dbf
  downloaded: sl8olre_p089r083_d2025091120260109_dlj-dlj-clear-ge80_e32756.prj
  downloaded: sl8olre_p089r083_d2025091120260109_dlj-dlj-clear-ge80_e32756.shp
  downloaded: sl8olre_p089r083_d2025091120260109_dlj-dlj-clear-ge80_e32756.shx
  downloaded: sl8olre_p089r083_d2025091120260109_dlj-dlj-strong-ge60_e32756.cpg
  downloaded: sl8olre_p089r083_d2025091120260109_dlj-dlj-strong-ge60_e32756.dbf
  downloaded: sl8olre_p089r083_d2025091120260109_dlj-dlj-strong-ge60_e32756.prj
  downloaded: sl8olre_p089r083_d2025091120260109_dlj-dlj-strong-ge60_e32756.shp
  downloaded: sl8olre_p089r083_d2025091120260109_dlj-dlj-strong-ge60_e32756.shx

Creating split ZIPs for p089r083
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r083_20250911.zip
  zipped: p089r083_20250911.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r083_20260109.zip
  zipped: p089r083_20260109.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r083_d2025091120260109.zip
  zipped: p089r083_d2025091120260109.zip (13 files)

Downloading p089r084
Tile folder: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r084
  downloaded: sl9olre_p089r084_20250911_ga0_e32756.tif
  downloaded: sl8olre_p089r084_20260109_ga0_e32756.tif
  downloaded: sl8olre_p089r084_d2025091120260109_dlj-dlj-clear-ge80_e32756.tif
  downloaded: sl8olre_p089r084_d2025091120260109_dlj-dlj-strong-ge60_e32756.tif
  downloaded: sl8olre_p089r084_d2025091120260109_dlj_e32756.tif
  downloaded: sl8olre_p089r084_d2025091120260109_dlj-dlj-clear-ge80_e32756.cpg
  downloaded: sl8olre_p089r084_d2025091120260109_dlj-dlj-clear-ge80_e32756.dbf
  downloaded: sl8olre_p089r084_d2025091120260109_dlj-dlj-clear-ge80_e32756.prj
  downloaded: sl8olre_p089r084_d2025091120260109_dlj-dlj-clear-ge80_e32756.shp
  downloaded: sl8olre_p089r084_d2025091120260109_dlj-dlj-clear-ge80_e32756.shx
  downloaded: sl8olre_p089r084_d2025091120260109_dlj-dlj-strong-ge60_e32756.cpg
  downloaded: sl8olre_p089r084_d2025091120260109_dlj-dlj-strong-ge60_e32756.dbf
  downloaded: sl8olre_p089r084_d2025091120260109_dlj-dlj-strong-ge60_e32756.prj
  downloaded: sl8olre_p089r084_d2025091120260109_dlj-dlj-strong-ge60_e32756.shp
  downloaded: sl8olre_p089r084_d2025091120260109_dlj-dlj-strong-ge60_e32756.shx

Creating split ZIPs for p089r084
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r084_20250911.zip
  zipped: p089r084_20250911.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r084_20260109.zip
  zipped: p089r084_20260109.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p089r084_d2025091120260109.zip
  zipped: p089r084_d2025091120260109.zip (13 files)

Downloading p090r077
Tile folder: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p090r077
  downloaded: sl9olre_p090r077_20250817_ga0_e32756.tif
  downloaded: sl9olre_p090r077_20260108_ga0_e32756.tif
  downloaded: sl9olre_p090r077_d2025081720260108_dlj-dlj-clear-ge80_e32756.tif
  downloaded: sl9olre_p090r077_d2025081720260108_dlj-dlj-strong-ge60_e32756.tif
  downloaded: sl9olre_p090r077_d2025081720260108_dlj_e32756.tif
  downloaded: sl9olre_p090r077_d2025081720260108_dlj-dlj-clear-ge80_e32756.cpg
  downloaded: sl9olre_p090r077_d2025081720260108_dlj-dlj-clear-ge80_e32756.dbf
  downloaded: sl9olre_p090r077_d2025081720260108_dlj-dlj-clear-ge80_e32756.prj
  downloaded: sl9olre_p090r077_d2025081720260108_dlj-dlj-clear-ge80_e32756.shp
  downloaded: sl9olre_p090r077_d2025081720260108_dlj-dlj-clear-ge80_e32756.shx
  downloaded: sl9olre_p090r077_d2025081720260108_dlj-dlj-strong-ge60_e32756.cpg
  downloaded: sl9olre_p090r077_d2025081720260108_dlj-dlj-strong-ge60_e32756.dbf
  downloaded: sl9olre_p090r077_d2025081720260108_dlj-dlj-strong-ge60_e32756.prj
  downloaded: sl9olre_p090r077_d2025081720260108_dlj-dlj-strong-ge60_e32756.shp
  downloaded: sl9olre_p090r077_d2025081720260108_dlj-dlj-strong-ge60_e32756.shx

Creating split ZIPs for p090r077
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p090r077_20250817.zip
  zipped: p090r077_20250817.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p090r077_20260108.zip
  zipped: p090r077_20260108.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p090r077_d2025081720260108.zip
  zipped: p090r077_d2025081720260108.zip (13 files)

Downloading p090r078
Tile folder: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p090r078
  downloaded: sl8olre_p090r078_20250910_ga0_e32756.tif
  downloaded: sl9olre_p090r078_20251207_ga0_e32756.tif
  downloaded: sl9olre_p090r078_d2025091020251207_dlj-dlj-clear-ge80_e32756.tif
  downloaded: sl9olre_p090r078_d2025091020251207_dlj-dlj-strong-ge60_e32756.tif
  downloaded: sl9olre_p090r078_d2025091020251207_dlj_e32756.tif
  downloaded: sl9olre_p090r078_d2025091020251207_dlj-dlj-clear-ge80_e32756.cpg
  downloaded: sl9olre_p090r078_d2025091020251207_dlj-dlj-clear-ge80_e32756.dbf
  downloaded: sl9olre_p090r078_d2025091020251207_dlj-dlj-clear-ge80_e32756.prj
  downloaded: sl9olre_p090r078_d2025091020251207_dlj-dlj-clear-ge80_e32756.shp
  downloaded: sl9olre_p090r078_d2025091020251207_dlj-dlj-clear-ge80_e32756.shx
  downloaded: sl9olre_p090r078_d2025091020251207_dlj-dlj-strong-ge60_e32756.cpg
  downloaded: sl9olre_p090r078_d2025091020251207_dlj-dlj-strong-ge60_e32756.dbf
  downloaded: sl9olre_p090r078_d2025091020251207_dlj-dlj-strong-ge60_e32756.prj
  downloaded: sl9olre_p090r078_d2025091020251207_dlj-dlj-strong-ge60_e32756.shp
  downloaded: sl9olre_p090r078_d2025091020251207_dlj-dlj-strong-ge60_e32756.shx

Creating split ZIPs for p090r078
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p090r078_20250910.zip
  zipped: p090r078_20250910.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p090r078_20251207.zip
  zipped: p090r078_20251207.zip (1 files)
  creating: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p090r078_d2025091020251207.zip
  zipped: p090r078_d2025091020251207.zip (13 files)

Downloading p090r079
Tile folder: /home/jovyan/work-easi-eds/output/eds_outputs_from_s3tiles/p090r079
  downloaded: sl9olre_p090r079_20251004_ga0_e32756.tif
  downloaded: sl8olre_p090r079_20251231_ga0_e32756.tif
  downloaded: sl8olre_p090r079_d2025100420251231_dlj-dlj-clear-ge80_e32756.tif
  downloaded: sl8olre_p090r079_d2025100420251231_dlj-dlj-strong-ge60_e32756.tif
  downloaded: sl8olre_p090r079_d2025100420251231_dlj_e32756.tif
  downloaded: sl8olre_p090r079_d2025100420251231_dlj-dlj-clear-ge80_e32756.cpg
  downloaded: sl8olre_p090r079_d2025100420251231_dlj-dlj-clear-ge80_e32756.dbf

In [ ]:
print("\nOutput directory:")
print(export_dir.resolve())

In [ ]:
import re
import shutil
from pathlib import Path
from zipfile import ZipFile, ZIP_DEFLATED

# SETTINGS
tile_to_process = "p089r078"
delete_unzipped_files = False   # True = delete files after zipping

print("="*60)
print(f"Output directory: {export_dir.resolve()}")
print(f"Processing tile: {tile_to_process}")
print("="*60)


def extract_date_group(filename: str) -> str:
    """
    Extract grouping token from filename.

    Examples:
    20250701
    d2025070120251208
    """
    m = re.search(r'(d\d{16})', filename)
    if m:
        return m.group(1)

    m = re.search(r'(?<!\d)(\d{8})(?!\d)', filename)
    if m:
        return m.group(1)

    return "unknown"


# filter dataframe
group = eds_df[eds_df["tile"] == tile_to_process]

tile_dir = export_dir / tile_to_process
tile_dir.mkdir(parents=True, exist_ok=True)

print(f"\nDownloading files to: {tile_dir.resolve()}")

downloaded_files = []

for _, row in group.iterrows():

    key = row["key"]
    local_path = tile_dir / row["file"]

    # skip if already downloaded
    if not local_path.exists():

        client.download_file(
            bucket,
            key,
            str(local_path)
        )

        print("  downloaded:", local_path.name)

    else:
        print("  exists:", local_path.name)

    downloaded_files.append(local_path)


# group files by date/date-range
files_by_group = {}

for file_path in downloaded_files:

    group_key = extract_date_group(file_path.name)

    files_by_group.setdefault(group_key, []).append(file_path)


print("\nCreating ZIP files:")

for group_key, file_list in sorted(files_by_group.items()):

    zip_path = export_dir / f"{tile_to_process}_{group_key}.zip"

    print(f"  creating {zip_path.name}")

    with ZipFile(zip_path, "w", compression=ZIP_DEFLATED) as zipf:

        for file_path in file_list:

            zipf.write(
                file_path,
                arcname=file_path.name
            )

    print(f"  zipped {len(file_list)} files")


# optionally delete original files
if delete_unzipped_files:

    for f in downloaded_files:

        if f.exists():
            f.unlink()

    print(f"\nDeleted unzipped files from {tile_dir}")